#! /bin/bash
(
    cd ./build && 
	echo "C_COMPILER  =${CMAKE_C_COMPILER:-<unset>}" &&
	echo "CXX_COMPILER=${CMAKE_CXX_COMPILER:-<unset>}" &&
	cmake .. && 
	make "${@}" && 
	echo "====RUN====" && 
	echo "exec ${@}" &&
	exec "${@}"
)