#! /bin/bash

(
    export CMAKE_C_COMPILER=$(which gcc); 
    export CMAKE_CXX_COMPILER=$(which g++); 

    cd build && 
	echo "C_COMPILER  =$CMAKE_C_COMPILER" &&
	echo "CXX_COMPILER=$CMAKE_CXX_COMPILER" &&
	cmake .. && 
	make MAKE_VERBOSE=1 all && 
	make MotorTest && 
	echo ==RUN== && 
	./MotorTest
)
											    
